language: python
python:
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3 libxml2 libxslt libtiff libjpeg webp little-cms2
# command to install dependencies
install: pip3 install -r doxhund/requirements.txt
before_script:
  - curl https://raw.githubusercontent.com/codelucas/newspaper/master/download_corpora.py | python3
  - python -m nltk.downloader averaged_perceptron_tagger words maxent_ne_chunker
# command to run tests
script: py.test -v tests
after_success: codecov